### ISSUE TITLE
Investigate Word Stemming of indexed content

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#819]
Currently `title` and `description` are stemmed using the Snowball stemming algorithm.

This can lead to some misleading search results, e.g.

- Snoop (dogg) / Snooping
- Park / Parking

**Comment by jamesgorrie** [comment]
@mchv How do you guys deal with fields that you need two different analysers on?

**Comment by jamesgorrie** [comment]
Having looked at this a while ago mulit-fields seemed good?
https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html

**Comment by mchv** [comment]
@jamesgorrie we currently don't. I think that is really difficult to get it right, and especially having good tuning that works for all your use case with multiple analyser. I think a better way, but may be more iterative, is to use exclusion when you find a case that does not work, see [configuring language   analyzers](https://www.elastic.co/guide/en/elasticsearch/guide/current/configuring-language-analyzers.html)

**Comment by kenoir** [comment]
@mchv that looks like a much simpler solution.

**Comment by kenoir** [comment]
@theefer it'll be where there's a semantic collision between the word senses of stemmed and unstemmed words. The classic snooping --> snoop (searches for "snoop dogg"). I'm not really sure how we'd work around this in the general case.

**Comment by kenoir** [comment]
I propose we use the "S-stemmer" described here: http://www.researchgate.net/publication/220433848_How_effective_is_suffixing

```
IF a word ends in “ies,” but not “eies” or “aies”
THEN “ies” - “v”
IF a word ends in “es,” but not “aes,” “ees,” or “oes”
THEN “es” - “e”
IF a word ends in 3,” but not “us” or ‘3s”
THEN 3” - NULL 
```

Stemming algorithm can be chosen as detailed here: https://www.elastic.co/guide/en/elasticsearch/guide/current/choosing-a-stemmer.html

**Comment by kenoir** [comment]
Currently I think we use the "Porter" stemming algorithm which seems more far reaching in what it chooses to stem.

**Comment by kenoir** [comment]
From http://www.researchgate.net/publication/220433848_How_effective_is_suffixing:

```
Porter (1980) developed a stemming algorithm that
looks for about 60 suffixes, producing word variant conflation
intermediate between a simple singular-plural technique
and Lovins algorithm. The multistep process uses a
successive removal of short suffixes, rather than a single
removal of the longest possible suffix.
```

**Comment by theefer** [comment]
Looks good

**Comment by kenoir** [comment]
So my understanding of what ElasticSearch is doing so far is:

When new documents are indexed it uses an [analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html) on certain fields. 

See: https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/elasticsearch/Mappings.scala#L13

An `analyzer` is made up of:
- A [Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html): Tokenizers are used to break a string down into a stream of terms or tokens.
- A [Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenfilters.html): Token filters accept a stream of tokens from a tokenizer and can modify tokens (eg lowercasing), delete tokens (eg remove stopwords) or add tokens (eg synonyms).
- A [Character Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-charfilters.html): Character filters are used to preprocess the string of characters before it is passed to the tokenizer.

We for the `description` and `title`fields use the [Snowball Analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-snowball-analyzer.html), which uses the [Snowball Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-snowball-tokenfilter.html).

**Note:** Snowball is a DSL for writing stemming algorithms: http://snowball.tartarus.org/texts/introduction.html

The `Snowball Token Filter` takes a language parameter that identifies the stemmer that will be used.

**I can't find where we specify a language**, so i'm assuming we use the default, which is "English": 

https://github.com/elastic/elasticsearch/blob/4c981ff4bfc250080d521af105b5e8589c9fc517/core/src/main/java/org/elasticsearch/index/analysis/SnowballAnalyzerProvider.java#L64 

The result of choosing a language is not well documented. Further consulting the Elasticsearch source indicates that choosing "English" has the same effect as "Lovins" or "Porter" in this context:

https://github.com/elastic/elasticsearch/blob/4c981ff4bfc250080d521af105b5e8589c9fc517/core/src/main/java/org/elasticsearch/index/analysis/SnowballAnalyzer.java#L74

**Note:** The "Lovins" Stemming algorithm seems to be a more time efficient version of the "Porter" algorithm: http://snowball.tartarus.org/algorithms/lovins/stemmer.html and precedes its invention.

**Comment by kenoir** [comment]
**A note on making any changes to analyzers:** It is likely we will have to perform a re-index to update documents indexed in the past.

**Comment by kenoir** [comment]
In order to make use of the `minimal_english` stemmer available we will need to use a [StemmerTokenFilter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html), and specify the required stemmer in it's configuration.

To make use of the `StemmerTokenFilter` we will need to use a [custom analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html) as it does not appear it is available as one of the pre-made analyzers. 

The `SnowballAnalyzer` uses the [Standard Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html) so we should probably continue to use that.

**TODO:**
- [ ] What Character Filter are we using now?
- [ ] What does this new config look like in JSON?

**Comment by kenoir** [comment]
Proposed analyzer configuration:

```json
{
  "settings": {
    "analysis": {
      "filter": {
        "s_stemmer": {
          "type":       "stemmer",
          "stopwords":  "minimal_english"
        }
      },
      "analyzer": {
        "english_s_stemmer": {
          "tokenizer":  "standard",
          "filter": [
            "lowercase",
            "s_stemmer"
          ]
        }
      }
    }
  }
}
```

**TODO:** 
- [ ] How does one go about settting the above configuration?

**Comment by theefer** [comment]
Lgtm

On Fri, 21 Aug 2015 08:59 Robert Kenny <notifications@github.com> wrote:

> Proposed analyzer configuration:
>
> {
>   "settings": {
>     "analysis": {
>       "filter": {
>         "s_stemmer": {
>           "type":       "stemmer",
>           "stopwords":  "minimal_english"
>         }
>       },
>       "analyzer": {
>         "english_s_stemmer": {
>           "tokenizer":  "standard",
>           "filter": [
>             "lowercase",
>             "s_stemmer"
>           ]
>         }
>       }
>     }
>   }
> }
>
> *TODO:*
>
>    - How does one go about settting the above configuration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/issues/819#issuecomment-133319904>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by kenoir** [comment]
**Setting configuration:**

One can PUT JSON to the Elasticsearch API when creating an index, e.g.

`PUT /images` <- Your raw JSON

However we currently configure our primary index (images) using the Java Client.

See: https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/elasticsearch/ElasticSearchClient.scala

When we reindex I suspect we will have to create the updated index with the desired settings, in a similar way to the Mappings are added.

*PR Incoming*

**Comment by theefer** [comment]
This was fixed.
